const apiKey = process.env.GEMINI_API_KEY;

export async function askGemini(
  code: string,
  action: string
) {
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is missing");
  }

  let instruction = "";

  if (action === "Explain") {
    instruction = `
Explain the following code in simple terms.
Break down the logic step by step.
Mention the important programming concepts used.
`;
  }

  if (action === "Debug") {
    instruction = `
Analyze the following code for errors or bugs.

Give:
1. What is wrong
2. Why it is wrong
3. How to fix it

If the code is correct, clearly say that.
`;
  }

  if (action === "Complexity") {
    instruction = `
Analyze the following code.

Give:
1. Time complexity
2. Space complexity
3. A short explanation
`;
  }

  const prompt = `
You are CodeMentor AI, a helpful programming assistant.

${instruction}

User's code or problem:

${code}

Keep the answer clear and beginner-friendly.
`;

  const response = await fetch(
    "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent",
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-goog-api-key": apiKey,
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: prompt,
              },
            ],
          },
        ],
      }),
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    console.error("Gemini API error:", errorText);
    throw new Error("Gemini API request failed");
  }

  const data = await response.json();

  return (
    data.candidates?.[0]?.content?.parts?.[0]?.text ||
    "No response generated by Gemini."
  );
}
